### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by allantokuda** [dhruvapanyam/chord-finder#1]
Hello, thank you for this wonderful project!

I don't see an open source license here, and I am wondering if am free to contribute or build from this? I would be happy to help add one to this project for you, if you are open to it?

https://choosealicense.com/

**Comment by dhruvapanyam** [comment]
Hello, very sorry for the delay.
This project hasn't been active for years now, and the code is most definitely very messy.
I've added the license, so feel free to contribute and suggest new things too!
